export const CHANGE_CART_QUANTITY = 'CHANGE_CART_QUANTITY';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const CLEAR_CART = 'CLEAR_CART';
export const SET_CART = 'SET_CART';