export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const UPDATE_SEARCHING = 'UPDATE_SEARCHING';
export const UPDATE_CATEOGRY = 'UPDATE_CATEOGRY';
export const UPDATE_SORT = 'UPDATE_SORT';
export const FAILED_SEARCH = 'FAILED_SEARCH';