export const SET_CHECKOUT_CART = 'SET_CHECKOUT_CART';
export const SET_CHECKOUT_SUBTOTAL = 'SET_CHECKOUT_SUBTOTAL';
export const SET_CHECKOUT_CUSTOMER_INFORMATION = 'SET_CHECKOUT_CUSTOMER_INFORMATION';
export const SET_MERCADOPAGO_ORDER = 'SET_MERCADOPAGO_ORDER';
export const CONFIRM_MERCADOPAGO_PAYMENT = 'CONFIRM_MERCADOPAGO_PAYMENT';
export const CONFIRM_STRIPE_PAYMENT = 'CONFIRM_STRIPE_PAYMENT';
export const CONFIRM_PAYMENT = 'CONFIRM_PAYMENT';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const SET_CHECKOUT_ERROR_MESSAGE = 'SET_CHECKOUT_ERROR_MESSAGE';
export const SET_CONFIRM_ORDER_SUCCESS_MESSAGE = 'SET_CONFIRM_ORDER_SUCCESS_MESSAGE';
export const SET_CONFIRM_ORDER_ERROR_MESSAGE = 'SET_CONFIRM_ORDER_ERROR_MESSAGE';
export const CLEAR_CHECKOUT_DATA = 'CLEAR_CHECKOUT_DATA';


