export const SET_CHECKOUT_CART = 'SET_CHECKOUT_CART';
export const SET_CHECKOUT_SUBTOTAL = 'SET_CHECKOUT_SUBTOTAL';
export const SET_CHECKOUT_CUSTOMER_INFORMATION = 'SET_CHECKOUT_CUSTOMER_INFORMATION';