export const SET_CHECKOUT_CART = 'SET_CHECKOUT_CART';
export const SET_CHECKOUT_SUBTOTAL = 'SET_CHECKOUT_SUBTOTAL';
export const SET_CHECKOUT_CUSTOMER_INFORMATION = 'SET_CHECKOUT_CUSTOMER_INFORMATION';
export const CONFIRM_STRIPE_PAYMENT = 'CONFIRM_STRIPE_PAYMENT';
export const SET_LOADING = 'SET_LOADING';