export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const ADD_URL_TO_DELETE = 'ADD_URL_TO_DELETE';
export const DELETE_IMAGES = 'DELETE_IMAGES';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
